[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "star-streaming-pipeline"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["requests==2.34.2", "pandas==2.0.3", "gtfs-realtime-bindings==2.2.0"]

[tool.setuptools.packages.find]
where = ["src"]